import { ArrowRight, BarChart3, Calendar, ChevronDown, Database, Download, Filter, Gauge, Layers3, Map, RefreshCw, Search, SlidersHorizontal, Target, TrendingUp, Waves } from 'lucide-react';
import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/layout/PageShell';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHeader } from '@/components/ui/Card';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { oceanWatchApi, type DataStats, type ForecastMetrics } from '@/lib/api/client';

export interface PlatformPageConfig {
  title: string;
  description: string;
  eyebrow?: string;
  badge?: string;
  type: 'explore' | 'hotspots' | 'forecast' | 'priority' | 'intelligence' | 'data' | 'models' | 'about';
}

export function PlatformPage({ config }: { config: PlatformPageConfig }) {
  return <div><PageHeader title={config.title} description={config.description} eyebrow={config.eyebrow}><Badge variant="neutral">{config.badge ?? 'Concept preview · data layer pending'}</Badge></PageHeader><div className="container-page py-12 lg:py-16">{config.type === 'about' ? <AboutContent /> : <PlatformContent type={config.type} />}</div></div>;
}

function PlatformContent({ type }: { type: PlatformPageConfig['type'] }) {
  if (type === 'explore') return <ExploreContent />;
  if (type === 'hotspots') return <HotspotsContent />;
  if (type === 'forecast') return <ForecastContent />;
  if (type === 'priority') return <PriorityContent />;
  if (type === 'intelligence') return <IntelligenceContent />;
  if (type === 'data') return <DataContent />;
  return <ModelsContent />;
}

function ExploreContent() {
  const [stats, setStats] = useState<DataStats | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { oceanWatchApi.getSummaryStatistics().then(setStats).catch((requestError: Error) => setError(requestError.message)); }, []);
  return <><SectionHeader eyebrow="Dataset overview" title="A structured foundation for discovery" description="The explore workspace will bring together the observation sources that power OceanWatch intelligence." /><div className="mt-10 grid gap-5 md:grid-cols-3"><MetricCard label="Observation records" value={stats ? stats.total_observations.toLocaleString() : '—'} change={error ?? (stats ? 'Backend data statistics' : 'Loading data statistics')} icon={Database} /><MetricCard label="Geographic coverage" value="—" change="Not exposed by the backend stats endpoint" icon={Map} /><MetricCard label="Latest observation" value="—" change="Not exposed by the backend stats endpoint" icon={Calendar} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_0.7fr]"><PlaceholderPanel title="Observation coverage" icon={Map}><div className="relative flex h-64 items-center justify-center overflow-hidden rounded-xl border border-ocean-200 bg-ocean-50 dot-pattern"><span className="relative rounded-lg bg-white px-3 py-2 text-xs font-medium text-ocean-600 shadow-card">Coordinate coverage is available in Data Explorer.</span></div></PlaceholderPanel><PlaceholderPanel title="Data sources" icon={Layers3}><div className="space-y-3"><SourceRow label="Marine observations" status="Backend connected" /><SourceRow label="Oceanographic context" status="Not available" /><SourceRow label="Coastal geography" status="Not available" /></div></PlaceholderPanel></div></>;
}

function HotspotsContent() { return <><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeader eyebrow="Spatial intelligence" title="Where pollution concentrates" description="DBSCAN-based clustering will surface meaningful geographic hotspots from marine observation data." /><Button variant="outline"><Download className="h-4 w-4" /> Export view</Button></div><div className="mt-10 grid gap-5 md:grid-cols-3"><MetricCard label="Detected hotspots" value="—" change="Waiting for observations" icon={Target} /><MetricCard label="Highest priority zone" value="—" change="Not yet calculated" icon={Gauge} /><MetricCard label="Clustering confidence" value="—" change="Model preview" icon={BarChart3} /></div><div className="mt-8"><PlaceholderPanel title="Pollution hotspot map" icon={Map} action={<Badge variant="cyan">DBSCAN clustering</Badge>}><MapPlaceholder large /></PlaceholderPanel></div></>; }

function ForecastContent() { return <><SectionHeader eyebrow="Predictive intelligence" title="Look ahead at pollution trends" description="Forecasting will help teams understand where pollution concentration may rise next and prepare an effective response." /><div className="mt-10 grid gap-5 md:grid-cols-3"><MetricCard label="Forecast horizon" value="30 days" change="Placeholder configuration" icon={Calendar} /><MetricCard label="Prediction confidence" value="—" change="Awaiting model run" icon={TrendingUp} /><MetricCard label="Trend direction" value="—" change="No forecast loaded" icon={BarChart3} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_0.6fr]"><PlaceholderPanel title="Projected pollution concentration" icon={TrendingUp} action={<Badge variant="teal">XGBoost prediction</Badge>}><ChartPlaceholder /></PlaceholderPanel><PlaceholderPanel title="Forecast controls" icon={SlidersHorizontal}><div className="space-y-4"><SelectPlaceholder label="Region" value="All regions" /><SelectPlaceholder label="Time horizon" value="Next 30 days" /><SelectPlaceholder label="Metric" value="Pollution concentration" /><Button className="w-full">Run forecast <ArrowRight className="h-4 w-4" /></Button></div></PlaceholderPanel></div></>; }

function PriorityContent() { return <><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeader eyebrow="Decision support" title="Prioritize where action matters most" description="A transparent weighted score will help cleanup teams compare locations and build a defensible response sequence." /><Button><RefreshCw className="h-4 w-4" /> Recalculate</Button></div><div className="mt-10 grid gap-5 md:grid-cols-3"><MetricCard label="Priority locations" value="—" change="No score generated" icon={Target} /><MetricCard label="Highest score" value="—" change="Awaiting model inputs" icon={Gauge} /><MetricCard label="Scoring factors" value="4" change="Configured factors" icon={SlidersHorizontal} /></div><div className="mt-8 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><PlaceholderPanel title="Priority score distribution" icon={Gauge}><div className="flex h-64 items-center justify-center rounded-xl border border-dashed border-ocean-300 bg-ocean-50"><span className="text-sm text-ocean-500">Score distribution placeholder</span></div></PlaceholderPanel><PlaceholderPanel title="Priority ranking" icon={Target} action={<Badge variant="neutral">Transparent scoring</Badge>}><div className="space-y-2"><RankRow rank="01" name="Northern coastal zone" score="—" /><RankRow rank="02" name="Western shelf zone" score="—" /><RankRow rank="03" name="Southern current zone" score="—" /><RankRow rank="04" name="Eastern nearshore zone" score="—" /></div></PlaceholderPanel></div></>; }

function IntelligenceContent() { return <><div className="grid gap-5 rounded-2xl bg-navy-950 p-6 text-white sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><Badge variant="cyan">Unified intelligence layer</Badge><h2 className="mt-4 text-2xl font-bold">One view from observation to action.</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-ocean-300">This overview will connect hotspot detection, forecasting, and cleanup prioritization into a single decision-ready workspace.</p></div><div className="flex h-24 w-24 items-center justify-center rounded-2xl border border-cyan-500/30 bg-cyan-500/10"><Waves className="h-10 w-10 text-cyan-400" /></div></div><div className="mt-8 grid gap-5 md:grid-cols-3"><IntelligenceCard icon={Map} label="Spatial signal" title="Hotspot detection" description="Identify concentrated pollution zones." path="/hotspots" /><IntelligenceCard icon={TrendingUp} label="Future signal" title="Pollution forecast" description="Anticipate changing concentration." path="/forecast" /><IntelligenceCard icon={Target} label="Action signal" title="Cleanup priority" description="Rank locations for intervention." path="/priority" /></div><div className="mt-8"><PlaceholderPanel title="Intelligence overview" icon={Gauge}><div className="grid gap-4 sm:grid-cols-3"><div className="h-32 rounded-xl border border-ocean-200 bg-ocean-50" /><div className="h-32 rounded-xl border border-ocean-200 bg-ocean-50" /><div className="h-32 rounded-xl border border-ocean-200 bg-ocean-50" /></div></PlaceholderPanel></div></>; }

function DataContent() { return <><SectionHeader eyebrow="Evidence workspace" title="Explore the observations behind the signal" description="Filter, inspect, and understand the structured records that will feed OceanWatch analysis." /><Card className="mt-10"><CardHeader><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="relative max-w-sm flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-ocean-400" /><input className="w-full rounded-lg border border-ocean-200 bg-ocean-50 py-2.5 pl-9 pr-3 text-sm text-navy-950 placeholder:text-ocean-400 focus:border-cyan-400 focus:outline-none focus:ring-2 focus:ring-cyan-100" placeholder="Search observations" disabled /></div><div className="flex gap-2"><Button variant="outline" size="sm"><Filter className="h-4 w-4" /> Filters</Button><Button variant="ghost" size="sm"><Download className="h-4 w-4" /> Export</Button></div></div></CardHeader><CardBody><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead><tr className="border-b border-ocean-200 text-xs uppercase tracking-wider text-ocean-500"><th className="pb-3 font-medium">Observation ID</th><th className="pb-3 font-medium">Location</th><th className="pb-3 font-medium">Observed</th><th className="pb-3 font-medium">Category</th><th className="pb-3 font-medium">Status</th></tr></thead><tbody>{['OW-0001', 'OW-0002', 'OW-0003', 'OW-0004'].map((id, index) => <tr key={id} className="border-b border-ocean-100 last:border-0"><td className="py-4 font-mono text-xs text-navy-800">{id}</td><td className="py-4 text-ocean-600">Awaiting connection</td><td className="py-4 text-ocean-600">—</td><td className="py-4"><Badge variant="neutral">Unclassified</Badge></td><td className="py-4 text-ocean-500">Placeholder row {index + 1}</td></tr>)}</tbody></table></div></CardBody></Card></>; }

function ModelsContent() {
  const [metrics, setMetrics] = useState<ForecastMetrics | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { oceanWatchApi.getModelMetrics().then(setMetrics).catch((requestError: Error) => setError(requestError.message)); }, []);
  const metricEntries = Object.entries(metrics?.metrics ?? {}).filter(([, value]) => typeof value === 'number') as [string, number][];
   return <><SectionHeader eyebrow="Model transparency" title="Understand the intelligence behind each output" description="OceanWatch is designed to make model performance, inputs, and limitations visible to the people using its recommendations." /><div className="mt-10 grid gap-5 md:grid-cols-3"><ModelCard title="DBSCAN" label="Hotspot detection" color="cyan" /><ModelCard title="XGBoost" label="Pollution forecasting" color="teal" /><ModelCard title="Weighted score" label="Cleanup prioritization" color="navy" /></div><Card className="mt-8"><CardBody><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><Badge variant="neutral">{metrics ? 'Backend metrics' : error ? 'Metrics unavailable' : 'Loading metrics'}</Badge><h3 className="mt-4 text-2xl font-bold text-navy-950">Forecast model performance</h3><p className="mt-3 text-sm leading-relaxed text-ocean-600">{error ?? metrics?.message ?? 'Loading the metrics exposed by the FastAPI model endpoint.'}</p></div><div className="rounded-xl border border-ocean-200 bg-ocean-50 p-5">{metricEntries.length ? <div className="grid gap-4 sm:grid-cols-2">{metricEntries.map(([label, value]) => <div key={label}><p className="text-xs uppercase tracking-wider text-ocean-500">{label}</p><p className="mt-1 font-mono text-xl font-semibold text-navy-950">{value.toFixed(4)}</p></div>)}</div> : <p className="text-sm text-ocean-500">No numeric model metrics are currently available.</p>}</div></div><p className="mt-6 border-t border-ocean-100 pt-4 text-xs leading-5 text-ocean-500">Feature importance, DBSCAN evaluation metrics, and priority distributions are not exposed by existing backend endpoints.</p></CardBody></Card></>;
}

function AboutContent() { return <div className="grid gap-14 lg:grid-cols-[0.9fr_1.1fr]"><div><SectionHeader eyebrow="The project" title="A clearer way to see marine plastic pollution." description="OceanWatch is a final-year major project exploring how data analytics and machine learning can support practical environmental decision-making." /><div className="mt-8 flex flex-wrap gap-2"><Badge variant="cyan">Environmental technology</Badge><Badge variant="teal">Data-informed action</Badge><Badge variant="navy">Research concept</Badge></div></div><div className="space-y-5"><Card><CardBody><div className="flex gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-cyan-100 text-cyan-700"><Waves className="h-5 w-5" /></div><div><h3 className="font-bold text-navy-950">The ambition</h3><p className="mt-2 text-sm leading-relaxed text-ocean-600">Make marine pollution intelligence more accessible, transparent, and useful for the people responsible for protecting coastal and ocean environments.</p></div></div></CardBody></Card><Card><CardBody><div className="flex gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-teal-100 text-teal-700"><Layers3 className="h-5 w-5" /></div><div><h3 className="font-bold text-navy-950">The foundation</h3><p className="mt-2 text-sm leading-relaxed text-ocean-600">A modular platform foundation designed to connect observation data, spatial analysis, predictive modelling, and decision support in one coherent experience.</p></div></div></CardBody></Card><Card><CardBody><div className="flex gap-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-navy-100 text-navy-700"><Target className="h-5 w-5" /></div><div><h3 className="font-bold text-navy-950">The next chapter</h3><p className="mt-2 text-sm leading-relaxed text-ocean-600">The frontend foundation is ready for validated datasets, model outputs, and user research to shape the next phase of the system.</p></div></div></CardBody></Card></div></div>; }

function MetricCard({ label, value, change, icon: Icon }: { label: string; value: string; change: string; icon: typeof Database }) { return <Card><CardBody><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-ocean-500">{label}</p><p className="mt-3 font-display text-3xl font-bold text-navy-950">{value}</p><p className="mt-2 text-xs text-ocean-500">{change}</p></div><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-ocean-100 text-ocean-700"><Icon className="h-5 w-5" /></div></div></CardBody></Card>; }

function PlaceholderPanel({ title, icon: Icon, action, children }: { title: string; icon: typeof Map; action?: React.ReactNode; children: React.ReactNode }) { return <Card><CardHeader><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-ocean-100 text-ocean-700"><Icon className="h-4 w-4" /></div><h3 className="text-sm font-bold text-navy-950">{title}</h3></div>{action}</div></CardHeader><CardBody>{children}</CardBody></Card>; }

function MapPlaceholder({ large = false }: { large?: boolean }) { return <div className={`relative flex ${large ? 'h-[28rem]' : 'h-64'} items-center justify-center overflow-hidden rounded-xl border border-ocean-200 bg-ocean-50 dot-pattern`}><div className="absolute left-[14%] top-[18%] h-28 w-44 rotate-12 rounded-[45%] border border-cyan-300/60 bg-cyan-100/30" /><div className="absolute left-[42%] top-[40%] h-36 w-52 -rotate-6 rounded-[55%] border border-teal-300/60 bg-teal-100/30" /><div className="absolute right-[12%] top-[20%] h-20 w-28 rotate-45 rounded-[50%] border border-ocean-300 bg-ocean-100/50" /><span className="relative rounded-lg bg-white px-4 py-2 text-xs font-medium text-ocean-600 shadow-card">Interactive map placeholder</span></div>; }
function ChartPlaceholder() { return <div className="relative h-64 rounded-xl border border-ocean-200 bg-ocean-50 p-5"><div className="absolute inset-x-5 top-5 flex justify-between text-[10px] text-ocean-400"><span>Today</span><span>+30 days</span></div><svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 240" preserveAspectRatio="none" aria-hidden="true"><path d="M0 195C80 180 100 150 160 170S250 120 300 140s70-40 120-22 100-44 180-68" fill="none" stroke="#14b8a6" strokeWidth="3" /><path d="M0 195C80 180 100 150 160 170S250 120 300 140" fill="none" stroke="#0e7490" strokeWidth="3" /></svg><div className="absolute bottom-5 left-5 flex items-center gap-4 text-[10px] text-ocean-500"><span className="flex items-center gap-1.5"><span className="h-1.5 w-5 rounded-full bg-teal-500" />Projected concentration</span><span className="flex items-center gap-1.5"><span className="h-1.5 w-5 rounded-full bg-ocean-700" />Observed</span></div></div>; }
function SourceRow({ label, status }: { label: string; status: string }) { return <div className="flex items-center justify-between gap-3 rounded-lg border border-ocean-100 bg-ocean-50 px-3 py-3"><span className="text-sm text-navy-800">{label}</span><span className="text-[10px] text-ocean-500">{status}</span></div>; }
function SelectPlaceholder({ label, value }: { label: string; value: string }) { return <div><label className="mb-1.5 block text-xs font-medium text-ocean-600">{label}</label><div className="flex items-center justify-between rounded-lg border border-ocean-200 bg-white px-3 py-2.5 text-sm text-ocean-600"><span>{value}</span><ChevronDown className="h-4 w-4 text-ocean-400" /></div></div>; }
function RankRow({ rank, name, score }: { rank: string; name: string; score: string }) { return <div className="flex items-center gap-3 rounded-lg border border-ocean-100 bg-ocean-50 px-4 py-3"><span className="font-mono text-xs text-cyan-600">{rank}</span><span className="flex-1 text-sm font-medium text-navy-800">{name}</span><span className="font-mono text-xs text-ocean-500">Score {score}</span></div>; }
function IntelligenceCard({ icon: Icon, label, title, description, path }: { icon: typeof Map; label: string; title: string; description: string; path: string }) { return <Card className="group hover:-translate-y-1 hover:shadow-card-hover"><CardBody><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-ocean-100 text-ocean-700"><Icon className="h-5 w-5" /></div><ArrowRight className="h-4 w-4 text-ocean-300 transition-transform group-hover:translate-x-1 group-hover:text-cyan-500" /></div><p className="mt-6 text-xs font-semibold uppercase tracking-wider text-cyan-600">{label}</p><h3 className="mt-2 text-lg font-bold text-navy-950">{title}</h3><p className="mt-2 text-sm text-ocean-600">{description}</p><Button to={path} variant="ghost" size="sm" className="mt-4 px-0 hover:bg-transparent">Open view <ArrowRight className="h-3.5 w-3.5" /></Button></CardBody></Card>; }
function ModelCard({ title, label, color }: { title: string; label: string; color: 'cyan' | 'teal' | 'navy' }) { return <Card><CardBody><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${color === 'cyan' ? 'bg-cyan-100 text-cyan-700' : color === 'teal' ? 'bg-teal-100 text-teal-700' : 'bg-navy-100 text-navy-700'}`}><BarChart3 className="h-5 w-5" /></div><h3 className="mt-6 font-display text-2xl font-bold text-navy-950">{title}</h3><p className="mt-1 text-sm text-ocean-600">{label}</p><div className="mt-6 flex items-center justify-between border-t border-ocean-100 pt-4 text-xs"><span className="text-ocean-500">Status</span><Badge variant="neutral">Preview</Badge></div></CardBody></Card>; }
